name: Hello HTML CI

on:
  push:
    branches: [ "main" ]

jobs:
  check-files:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code du repo
        uses: actions/checkout@v4

      - name: Vérifier que les fichiers existent
        run: |
          ls
          test -f index.html
          test -f style.css